[pytest]
testpaths = tests
addopts = -v --tb=short
markers =
    e2e
    contract
    api
    
filterwarnings =
    ignore::DeprecationWarning:openapi_core.*

log_cli = true
log_cli_level = INFO
log_cli_format = %(levelname)s %(message)s
log_cli_date_format = %H:%M:%S